openapi: 3.1.0
info:
  version: 1.0.0
  title: Phonebook
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of phonebook for personal or corporate use
tags:
  - name: Contacts
    description: Operations with contacts
  - name: Auth
    description: Operation with user
servers:
  - url: http://127.0.0.1:3000
  - url: https://nodejs-hw7-swagger-p0s5.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    put:
      $ref: '../swagger/paths/contacts/{id}/put.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /register:
    post:
      $ref: '../swagger/paths/auth/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer